package com.egormoroz.schooly;

public enum ErrorList {
    TO_MANY_REQUESTS_ERROR,
    UNKNOWN_REGISTRATION_ERROR,
    WRONG_SMS_CODE_ERROR,
    WRONG_PHONE_NUMBER_ERROR,
    SMS_LIMIT_ERROR,
    NOT_ENOUGH_SYMBOL_ERROR,
    ONLY_ENGLISH_SYMBOLS_ERROR,
    INVALID_SYMBOLS_ERROR,
    NOT_ONLY_NUMBERS_ERROR,
    NOT_ONLY_LETTERS,
    NOTHING,
    NICK_IS_USED,
    PHONE_ERROR,
    ERROR_EMPTY_PHONE,
    ERROR_EMPTY_NICK,
    ERROR_NICK_IS_TO_SHORT
}